name: LaTeX
on: push

jobs:
  compile:
    name: Compile LaTeX
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Compile LaTeX files
        uses: birjolaxew/tectonic-biber-action@master
        with:
          files: |
            proposal/proposal.tex
      - name: Upload PDF
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: proposal.pdf
          path: proposal/proposal.pdf
