name: LaTeX
on: push

jobs:
  compile:
    name: Compile LaTeX
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run compiler
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            proposal/proposal.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          path: proposal/proposal.pdf
